# application
spring:
  application:
    name: baojie-service
  datasource:
    druid:
      username: root
      password: Mysql615243!
      url: jdbc:mysql://119.29.239.91:3306/foreach?useSSL=false&useUnicode=true&characterEncoding=utf8
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5

# dubbo
dubbo:
  scan:
    basePackages: com.baojie.service.impl
  application:
    id: rbjService
    name: rbjServiceName
    qosEnable: false
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    id: rbjZookeeper
    address: zookeeper://119.29.239.91:2181?client=curator

# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      dbType: mysql
      idType: auto
    refresh: false
  configuration:
    cacheEnabled: false

